default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  host: dpg-d023h63uibrs73aggscg-a.ohio-postgres.render.com
  database: sewcial
  username: sewcial_user
  password: h3q9I2GHeopgLUKBEprTiOZhPi7kyc1R

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

cable:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

queue:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
